"""add parcel_number_counter table

Revision ID: 3d4c40663f2d
Revises: 590fb67209c6
Create Date: 2025-07-21 13:05:20.883371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d4c40663f2d'
down_revision: Union[str, Sequence[str], None] = '590fb67209c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel_number_counter',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('current', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'api_keys', ['id'])
    op.create_unique_constraint(None, 'clients', ['id'])
    op.create_unique_constraint(None, 'dispatches', ['id'])
    op.create_unique_constraint(None, 'shipment_items', ['id'])
    op.create_unique_constraint(None, 'shipment_statuses', ['id'])
    op.create_unique_constraint(None, 'shipments', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'shipments', type_='unique')
    op.drop_constraint(None, 'shipment_statuses', type_='unique')
    op.drop_constraint(None, 'shipment_items', type_='unique')
    op.drop_constraint(None, 'dispatches', type_='unique')
    op.drop_constraint(None, 'clients', type_='unique')
    op.drop_constraint(None, 'api_keys', type_='unique')
    op.drop_table('parcel_number_counter')
    # ### end Alembic commands ###
