"""add client_tarif table

Revision ID: 43a71b36c18c
Revises: 3d4c40663f2d
Create Date: 2025-07-21 13:18:39.110085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a71b36c18c'
down_revision: Union[str, Sequence[str], None] = '3d4c40663f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_tariffs',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('min_weight', sa.Numeric(), nullable=False),
    sa.Column('max_weight', sa.Numeric(), nullable=True),
    sa.Column('price_per_kg', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_tariffs')
    # ### end Alembic commands ###
