"""clean init

Revision ID: 590fb67209c6
Revises: 
Create Date: 2025-07-21 13:03:38.385854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '590fb67209c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('dispatches',
    sa.Column('dispatch_number', sa.String(), nullable=False),
    sa.Column('pits_dispatch_id', sa.String(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('shipments',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('dispatch_id', sa.UUID(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(), nullable=True),
    sa.Column('receiver_name', sa.String(), nullable=True),
    sa.Column('receiver_phone', sa.String(), nullable=True),
    sa.Column('receiver_country', sa.String(), nullable=True),
    sa.Column('receiver_area_id', sa.String(), nullable=True),
    sa.Column('receiver_city_id', sa.String(), nullable=True),
    sa.Column('receiver_street_id', sa.String(), nullable=True),
    sa.Column('receiver_house', sa.String(), nullable=True),
    sa.Column('receiver_flat', sa.String(), nullable=True),
    sa.Column('receiver_zip', sa.String(), nullable=True),
    sa.Column('receiver_branch_id', sa.String(), nullable=True),
    sa.Column('receiver_branch_name', sa.String(), nullable=True),
    sa.Column('receiver_branch_number', sa.String(), nullable=True),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.Column('length', sa.Numeric(), nullable=True),
    sa.Column('width', sa.Numeric(), nullable=True),
    sa.Column('height', sa.Numeric(), nullable=True),
    sa.Column('declared_value', sa.Numeric(), nullable=True),
    sa.Column('value_currency', sa.String(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('is_cod', sa.Boolean(), nullable=True),
    sa.Column('cod_amount', sa.Numeric(), nullable=True),
    sa.Column('label_path', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('tracking_number')
    )
    op.create_table('shipment_items',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('value_currency', sa.String(), nullable=True),
    sa.Column('hs_code', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('shipment_statuses',
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('status_code', sa.String(), nullable=True),
    sa.Column('status_text', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_statuses')
    op.drop_table('shipment_items')
    op.drop_table('shipments')
    op.drop_table('users')
    op.drop_table('dispatches')
    op.drop_table('api_keys')
    op.drop_table('clients')
    # ### end Alembic commands ###
